CREATE SCHEMA RDW_CFG;
CREATE TABLE RDW_CFG.RDW_CFG_PKG_EXE_LOG (
    LOG_ID INT IDENTITY(1,1) PRIMARY KEY,
    PACKAGE_NAME VARCHAR(255) NOT NULL,
    TASK_NAME VARCHAR(255),
    EXECUTION_STATUS VARCHAR(50) NOT NULL,
    ERROR_MESSAGE VARCHAR(MAX),
    START_TIME DATETIME NOT NULL,
    END_TIME DATETIME,
    DURATION_IN_SECONDS INT,
    LOG_TIMESTAMP DATETIME DEFAULT GETDATE()
);
