CREATE TABLE RDW_STG.RDW_STG_PRODUCT_CLOTHING (
    ProductCode VARCHAR(50) PRIMARY KEY,
    ProductName VARCHAR(255) NOT NULL,
    Category VARCHAR(100) NOT NULL,
    Price VARCHAR(50) NOT NULL
);
CREATE TABLE RDW_STG.RDW_STG_PRODUCT_FURNITURE (
    ProductCode VARCHAR(50) PRIMARY KEY,
    ProductName VARCHAR(255) NOT NULL,
    Category VARCHAR(100) NOT NULL,
    Price VARCHAR(50) NOT NULL
);
CREATE TABLE RDW_STG.RDW_STG_PRODUCT_ELECTRONICS (
    ProductCode VARCHAR(50) PRIMARY KEY,
    ProductName VARCHAR(255) NOT NULL,
    Category VARCHAR(100) NOT NULL,
    Price VARCHAR(50) NOT NULL
);