CREATE TABLE RDW_STG.SALESTRANSACTION (
    TRANSACTIONID VARCHAR(50),
    CUSTOMERFULLNAME VARCHAR(255),
    TRANSACTIONDATE VARCHAR(50),
    PRODUCTCODE VARCHAR(50),
    ITEMSSOLD VARCHAR(50),
    TOTALAMOUNT VARCHAR(50),
    PRODUCTCATEGORY VARCHAR(100),
    SALEREGION VARCHAR(50),
    TRANSACTIONSTATUS VARCHAR(20)
);

CREATE TABLE Destination (
    SaleID VARCHAR(50),
    CustomerName VARCHAR(50),
    SaleDate VARCHAR(50),
    ProductID VARCHAR(50),
    Quantity VARCHAR(50),
    Amount VARCHAR(50),
    Category VARCHAR(50),
    Region VARCHAR(50),
    Status VARCHAR(50)
)