CREATE PROCEDURE RDW_SP_DM_SLS_ITM_A
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO RDW_DM.RDW_DM_SLS_ITM_A (PRODUCT_CODE, PRODUCT_NAME, TOTAL_QUANTITY, TOTAL_SALES)
    SELECT 
        S.PRD_CDE AS PRODUCT_CODE,
        P.ProductName AS PRODUCT_NAME,
        SUM(S.F_QTY) AS TOTAL_QUANTITY,
        SUM(S.F_SLS) AS TOTAL_SALES
    FROM RDW_TGT.RDW_TGT_SALESTRANSACTION S
    INNER JOIN RDW_TGT.RDW_TGT_PRODUCT P ON S.PRD_CDE = P.ProductCode
    GROUP BY S.PRD_CDE, P.ProductName;
END;
