CREATE PROCEDURE RDW_SP_TRUNCATE_ALL_TABLES
AS
BEGIN
    SET NOCOUNT ON;

    -- Truncate Data Mart Tables
    TRUNCATE TABLE RDW_DM.RDW_DM_SLS_YR_A;
    TRUNCATE TABLE RDW_DM.RDW_DM_SLS_ITM_A;
    TRUNCATE TABLE RDW_DM.RDW_DM_SLS_YR_ITM_A;

    -- Truncate Target Tables
    TRUNCATE TABLE RDW_TGT.RDW_TGT_SALESTRANSACTION;
    TRUNCATE TABLE RDW_TGT.RDW_TGT_PRODUCT;
END;