CREATE PROCEDURE RDW_SP_DM_SLS_YR_A
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO RDW_DM.RDW_DM_SLS_YR_A (YEAR, TOTAL_QUANTITY, TOTAL_SALES)
    SELECT 
        YEAR(TXN_DT) AS YEAR,
        SUM(F_QTY) AS TOTAL_QUANTITY,
        SUM(F_SLS) AS TOTAL_SALES
    FROM RDW_TGT.RDW_TGT_SALESTRANSACTION
    GROUP BY YEAR(TXN_DT);
END;
