CREATE TABLE RDW_DM.RDW_DM_SLS_YR_ITM_A (
    YEAR INT,
    PRODUCT_CODE INT,
    PRODUCT_NAME VARCHAR(255),
    TOTAL_QUANTITY BIGINT,
    TOTAL_SALES DECIMAL(18, 2),
    PRIMARY KEY (YEAR, PRODUCT_CODE)
);
