CREATE SCHEMA RDW_DM;
CREATE TABLE RDW_DM.RDW_DM_SLS_YR_A (
    SALEYEAR INT NOT NULL,              -- YEAR OF THE SALES
    PRODUCTCATEGORY VARCHAR(100) NOT NULL, -- CATEGORY OF THE PRODUCT
    PRODUCTNAME VARCHAR(200) NOT NULL,  -- NAME OF THE PRODUCT
    TOTALUNITSSOLD INT NOT NULL,        -- TOTAL NUMBER OF UNITS SOLD
    TOTALSALESAMOUNT FLOAT NOT NULL     -- TOTAL SALES AMOUNT IN CURRENCY
);